class WebServiceConstants:
    API_PREFIX = 'am-uds-dapa'
    COLLECTIONS = 'collections'
    CATALOG = 'catalog'
    DEPLOYED_STAGE = 'deployed_stage'
    BASE_URL = 'UDS_BASE_URL'
    ITEMS = 'items'
    ADMIN = 'admin'
    MISC = 'misc'
    STAC_BROWSER = 'stac_browser'
    STATIC_PARENT_DIR = 'STATIC_PARENT_DIR'
    STATIC_PARENT_DIR_DEFAULT = '/var/task/cumulus_lambda_functions/uds_api/'
    STAC_BROWSER_REPLACING_PREFIX = '/to/be/replaced/stac_browser'
